import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "@/components/nav+footer/nav/nav";
import Footer from "@/components/nav+footer/footer/footer";
import { Toaster } from "react-hot-toast";
import AuthProvider from "@/context/AuthProviders";
import { Poppins } from "next/font/google";
const poppins = Poppins({
  weight: ["400", "400"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Cars",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        <body className={poppins.className}>
          <Toaster
            toastOptions={{
              style: {
                background: "rgb(0, 114, 145)",
                color: "white",
              },
            }}
          />

          <Nav />
          {children}
          <Footer />
        </body>
      </AuthProvider>
    </html>
  );
}
